doctrine:
    dbal:
        #url: mysql://symfony:symfony@jc-mysql:3306/symfony
        #url: 'mysql://%env(string:DB_USER)%:%env(string:DB_PASSWORD)%@%env(string:DB_HOST)%:%env(string:DB_PORT)%/%env(string:DB_NAME)%'
        dbname: '%env(string:DB_NAME)%'
        user: '%env(string:DB_USER)%'
        password: '%env(string:DB_PASSWORD)%'
        host: '%env(string:DB_HOST)%'
        port: '%env(string:DB_PORT)%'
        driver: pdo_mysql

                #server_version: '8'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
